-- ==========================================
-- 1. 사용자(users) 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    login_id TEXT UNIQUE NOT NULL, 
    email TEXT UNIQUE NOT NULL,
    pw TEXT NOT NULL,                               
    name TEXT NOT NULL,            
    nickname TEXT NOT NULL,                                
    gender TEXT,
    
    -- [추가] user_profile.py의 체형 정보 저장을 위한 컬럼
    height NUMERIC(4, 1),      -- 소수점 1자리 허용 (예: 175.5)
    weight NUMERIC(4, 1),
    body_shape TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. 의류(clothes) 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS clothes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE, 
    
    -- [필수 카테고리 정보] 
    main_category TEXT NOT NULL,                         
    sub_category TEXT NOT NULL,                          
    name TEXT NOT NULL,                                  
  
    -- [추천 알고리즘 핵심 데이터]
    temp_level INTEGER NOT NULL,                         
    color TEXT NOT NULL,                                 
    style TEXT[] DEFAULT '{}'::TEXT[],                   
    fit TEXT DEFAULT '레귤러핏',                           -- [추가] 핏(Fit) 정보 저장 컬럼
    
    -- [AI 이미지 분석 및 부가 정보]
    image_url TEXT,                                      
    ai_tags TEXT[] DEFAULT '{}'::TEXT[],                 
    is_verified BOOLEAN DEFAULT false,                   
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. 데이터베이스 성능 최적화 (인덱스 설정)
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_clothes_recommend_search 
ON clothes (user_email, main_category, temp_level, sub_category);
