-- ==========================================
-- 1. 사용자(users) 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    login_id TEXT UNIQUE NOT NULL, 
    email TEXT UNIQUE NOT NULL,
    pw TEXT NOT NULL,                               
    name TEXT NOT NULL,            
    nickname TEXT NOT NULL,                                
    gender TEXT,
    
    -- 체형 맞춤 및 핏 추천 연동 컬럼
    height NUMERIC(4, 1),
    weight NUMERIC(4, 1),
    body_shape TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. 의류(clothes) 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS clothes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE, 
    main_category TEXT NOT NULL,                         
    sub_category TEXT NOT NULL,                          
    name TEXT NOT NULL,                                  
  
    -- 추천 알고리즘용 핵심 데이터
    temp_level INTEGER NOT NULL,                         
    color TEXT NOT NULL,                                 
    style TEXT[] DEFAULT '{}'::TEXT[],                   
    fit TEXT DEFAULT '스탠다드핏',  
    
    -- 사용자 실제 착용 데이터 트래킹
    monthly_wear_count INTEGER DEFAULT 0,
    last_worn_date TIMESTAMP WITH TIME ZONE,
    
    -- AI 분석 및 데이터 상태 관리
    image_url TEXT,                                      
    ai_tags TEXT[] DEFAULT '{}'::TEXT[],                 
    is_verified BOOLEAN DEFAULT false,                   
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. 코디 스크랩(scrapped_outfits) 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS scrapped_outfits (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE, 
    top_ids BIGINT[] NOT NULL,                                 
    bottom_id BIGINT REFERENCES clothes(id) ON DELETE CASCADE, 
    shoes_id BIGINT REFERENCES clothes(id) ON DELETE SET NULL,

    title TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 4. 데이터베이스 성능 최적화 (인덱스 설정)
-- ==========================================
-- 기온별/카테고리별 추천 연산 속도를 가속하기 위한 복합 인덱스
CREATE INDEX IF NOT EXISTS idx_clothes_recommend_search 
ON clothes (user_email, main_category, temp_level, sub_category);

-- 내 스크랩 룩북 목록을 빠르게 조회하기 위한 인덱스
CREATE INDEX IF NOT EXISTS idx_scraps_user_search 
ON scrapped_outfits (user_email);
