-- ==========================================
-- 1. 사용자(users) 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    login_id TEXT UNIQUE NOT NULL, 
    email TEXT UNIQUE NOT NULL,
    pw TEXT NOT NULL,                               
    name TEXT NOT NULL,            
    nickname TEXT NOT NULL,                                
    gender TEXT,
    
    -- [체형 및 프로필] 체형 가이드 및 핏 추천 연동용 컬럼
    height NUMERIC(4, 1),
    weight NUMERIC(4, 1),
    body_shape TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. 의류(clothes) 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS clothes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE, 
    
    -- [필수 카테고리 정보] 
    main_category TEXT NOT NULL,                         
    sub_category TEXT NOT NULL,                          
    name TEXT NOT NULL,                                  
  
    -- [추천 알고리즘 핵심 데이터]
    temp_level INTEGER NOT NULL,                         
    color TEXT NOT NULL,                                 
    style TEXT[] DEFAULT '{}'::TEXT[],                   
    fit TEXT DEFAULT '스탠다드핏',  
    
    -- [AI 이미지 분석 및 부가 정보]
    image_url TEXT,                                      
    ai_tags TEXT[] DEFAULT '{}'::TEXT[],                 
    is_verified BOOLEAN DEFAULT false,                   
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. 코디 스크랩(scrapped_outfits) 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS scrapped_outfits (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE, -- 스크랩한 유저
    
    -- 코디 구성 요소 저장
    top_ids BIGINT[] NOT NULL,                                 -- 상의 이너/아우터 ID 배열
    bottom_id BIGINT REFERENCES clothes(id) ON DELETE CASCADE, -- 하의 ID
    title TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 4. 데이터베이스 성능 최적화 (인덱스 설정)
-- ==========================================
-- 기온별/카테고리별 추천 연산 속도를 가속하기 위한 복합 인덱스
CREATE INDEX IF NOT EXISTS idx_clothes_recommend_search 
ON clothes (user_email, main_category, temp_level, sub_category);

-- 내 스크랩 룩북 목록을 빠르게 조회하기 위한 인덱스
CREATE INDEX IF NOT EXISTS idx_scraps_user_search 
ON scrapped_outfits (user_email);
