-- 1. 사용자(users) 테이블 생성
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- 고유 ID 자동 생성
    pw TEXT NOT NULL,                              -- 비밀번호
    nickname TEXT NOT NULL,                        -- 닉네임
    gender TEXT,                                   -- 성별
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- 2. 의류(clothes) 테이블 생성
CREATE TABLE clothes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE, -- users 테이블의 id와 연결
    main_category TEXT NOT NULL, -- 예시: '상의', '하의'
    sub_category TEXT NOT NULL,  -- 예시: '아우터', '이너', '바지', '치마'
    -- 옷 세부 정보
    name TEXT NOT NULL,          -- 옷 명칭 예시: ('코트')
    temp_level INTEGER,          -- 온도 레벨
    color TEXT,                  -- 색상
    style TEXT[]                 -- 스타일 (배열)
);
